MERGE INTO MEMBER
USING DUAL ON (MEM_ID = 1)
WHEN NOT MATCHED THEN INSERT (MEM_ID, MEM_CNO, MEM_LGN_ID, MEM_LGN_PW, MEM_NM) VALUES (1, '010-5678-1234', 'user1', '$2a$10$9oIJzR5sOUsXDpRb3nCY2.GtLvzjqBTWDhPpiD3NL1Gj80SMSqh7u', '유저1');

MERGE INTO MEMBER
USING DUAL ON (MEM_ID = 2)
WHEN NOT MATCHED THEN INSERT (MEM_ID, MEM_CNO, MEM_LGN_ID, MEM_LGN_PW, MEM_NM) VALUES (2, '010-4343-1234', 'user2', '$2a$10$9oIJzR5sOUsXDpRb3nCY2.GtLvzjqBTWDhPpiD3NL1Gj80SMSqh7u', '유저2');

MERGE INTO MEMBER_ROLE
USING DUAL ON (ROLE_ID = 1)
WHEN NOT MATCHED THEN INSERT (ROLE_ID, MEM_ID, ROLE_NM) VALUES (1, 1, 'ADM');

MERGE INTO MEMBER_ROLE
USING DUAL ON (ROLE_ID = 2)
WHEN NOT MATCHED THEN INSERT (ROLE_ID, MEM_ID, ROLE_NM)  VALUES (2, 1, 'USR');

MERGE INTO MEMBER_ROLE
USING DUAL ON (ROLE_ID = 3)
WHEN NOT MATCHED THEN INSERT (ROLE_ID, MEM_ID, ROLE_NM)  VALUES (3, 2, 'USR');
